/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathiasbattistella.vista;

import java.awt.Dimension;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import mathiasbattistella.vista.jinternalframes.administracion.VentanaCategorias;
import mathiasbattistella.vista.jinternalframes.administracion.VentanaMovimientoMensual;
import mathiasbattistella.vista.jinternalframes.administracion.VentanaMovimientoRapido;
import mathiasbattistella.vista.jinternalframes.listados.VentanaListadoDeImpagos;
import mathiasbattistella.vista.jinternalframes.listados.VentanaListadoMovimientos;
import mathiasbattistella.vista.jinternalframes.listados.VentanaListadoPorCategorias;
import mathiasbattistella.vista.jinternalframes.listados.VentanaBalances;
import java.util.Properties;

/**
 *
 * @author user6
 */
public class Inicio extends javax.swing.JFrame {

    private VentanaListadoMovimientos ventana_listado_movimientos;
    private VentanaListadoPorCategorias ventana_listado_categorias;
    private VentanaCategorias ventana_categorias;
    private VentanaMovimientoRapido ventana_movimiento_rapido;
    private VentanaMovimientoMensual ventana_movimiento_mensual;
    private VentanaBalances ventana_resumen;
    private VentanaListadoDeImpagos ventana_listado_de_impagos;    
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        try {
                /*
                    Carga del archivo de configuracion de la base datos
                */
                FileInputStream propFile = new FileInputStream("Archivos\\db\\datosdb.txt");
                Properties p = new Properties(System.getProperties());
                p.load(propFile);
                System.setProperties(p);
                if (System.getProperty("mostrarpropierties").compareTo("si") == 0) {
                    System.getProperties().list(System.out);
                }
                fondo.setBorder(new ImagenFondo());
                this.setExtendedState(Inicio.MAXIMIZED_BOTH);
                this.setIconImage(new ImageIcon(getClass().getResource("/mathiasbattistella/utilidades/icono.png")).getImage());
                this.setTitle("Mís Finanzas");        
                JOptionPane.showMessageDialog(fondo, "Bienvenido al sistema Mis Finanzas(c) 2016","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
        } catch (Error e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(-1);
        } catch (java.io.FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el archivo de configuracion" + e);
            System.exit(-1);
        } catch (java.io.IOException w) {
            JOptionPane.showMessageDialog(null, "Ocurrio algun error de I/O");
            System.exit(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo abrir la ventana ","Problema",JOptionPane.ERROR_MESSAGE);
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Resumen = new javax.swing.JMenuItem();
        MovimientoRapido = new javax.swing.JMenuItem();
        MovimientoMensual = new javax.swing.JMenuItem();
        Categoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MovimientosPagos = new javax.swing.JMenuItem();
        MovimientosImpagos = new javax.swing.JMenuItem();
        MovimientosPorCategorias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AcercaDe = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jMenu1.setText("Administrar");

        Resumen.setText("Balances");
        Resumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumenActionPerformed(evt);
            }
        });
        jMenu1.add(Resumen);

        MovimientoRapido.setText("Movimiento Rápido");
        MovimientoRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientoRapidoActionPerformed(evt);
            }
        });
        jMenu1.add(MovimientoRapido);

        MovimientoMensual.setText("Movimiento Mensual");
        MovimientoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientoMensualActionPerformed(evt);
            }
        });
        jMenu1.add(MovimientoMensual);

        Categoria.setText("Categorías");
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(Categoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        MovimientosPagos.setText("Movimentos Pagos");
        MovimientosPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosPagosActionPerformed(evt);
            }
        });
        jMenu2.add(MovimientosPagos);

        MovimientosImpagos.setText("Movimientos Impagos");
        MovimientosImpagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosImpagosActionPerformed(evt);
            }
        });
        jMenu2.add(MovimientosImpagos);

        MovimientosPorCategorias.setText("Movimientos por Categorías");
        MovimientosPorCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosPorCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(MovimientosPorCategorias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        AcercaDe.setText("Acerca de...");
        AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeActionPerformed(evt);
            }
        });
        jMenu3.add(AcercaDe);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu3.add(Salir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovimientosPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosPagosActionPerformed
        // TODO add your handling code here:
        try {
            ventana_listado_movimientos = new VentanaListadoMovimientos();
            ventana_listado_movimientos.setTitle("Listado de Movimientos Pagos");
            fondo.add(ventana_listado_movimientos);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_listado_movimientos.getSize();
            ventana_listado_movimientos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);      
            ventana_listado_movimientos.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_listado_movimientos.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }      
        
    }//GEN-LAST:event_MovimientosPagosActionPerformed

    private void MovimientoRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientoRapidoActionPerformed
       try{
            ventana_movimiento_rapido = new VentanaMovimientoRapido();
            ventana_movimiento_rapido.setTitle("Movimiento Rápido");
            fondo.add(ventana_movimiento_rapido);
            ventana_movimiento_rapido.setVisible(true);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_movimiento_rapido.getSize();
            ventana_movimiento_rapido.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_movimiento_rapido.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }                  
    }//GEN-LAST:event_MovimientoRapidoActionPerformed

    private void MovimientoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientoMensualActionPerformed
        try{
            ventana_movimiento_mensual = new VentanaMovimientoMensual();
            ventana_movimiento_mensual.setTitle("Movimiento Mensual");
            fondo.add(ventana_movimiento_mensual);
            ventana_movimiento_mensual.setVisible(true);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_movimiento_mensual.getSize();
            ventana_movimiento_mensual.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_movimiento_mensual.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }                   
    }//GEN-LAST:event_MovimientoMensualActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
        try{
            ventana_categorias = new VentanaCategorias();
            ventana_categorias.setTitle("Administrar Categorías");
            fondo.add(ventana_categorias);
            ventana_categorias.setVisible(true);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_categorias.getSize();
            ventana_categorias.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_categorias.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }            
    }//GEN-LAST:event_CategoriaActionPerformed

    private void MovimientosPorCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosPorCategoriasActionPerformed
        try{
            ventana_listado_categorias = new VentanaListadoPorCategorias();
            ventana_listado_categorias.setTitle("Listar Moviemientos por Categorías");
            fondo.add(ventana_listado_categorias);
            ventana_listado_categorias.setVisible(true);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_listado_categorias.getSize();
            ventana_listado_categorias.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_listado_categorias.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_MovimientosPorCategoriasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(fondo, "¿Seguro que desea Salir?", ":(", 0);
        if (opcion == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(fondo, "Proyecto de Java 2016 con MDI\nMathias Battistella","Acerca de...",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AcercaDeActionPerformed

    private void ResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumenActionPerformed
        try {
            ventana_resumen = new VentanaBalances();
            ventana_resumen.setTitle("Balances");  
            fondo.add(ventana_resumen);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_resumen.getSize();
            ventana_resumen.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
            ventana_resumen.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_resumen.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ResumenActionPerformed

    private void MovimientosImpagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosImpagosActionPerformed
        try {
            ventana_listado_de_impagos = new VentanaListadoDeImpagos();
            ventana_listado_de_impagos.setTitle("Listar Movimientos Impagos");  
            fondo.add(ventana_listado_de_impagos);
            Dimension desktopSize = fondo.getSize();
            Dimension FrameSize = ventana_listado_de_impagos.getSize();
            ventana_listado_de_impagos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
            ventana_listado_de_impagos.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fondo, "No se pudo abrir la ventana " + ventana_listado_de_impagos.getTitle(),"Problema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MovimientosImpagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    
 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDe;
    private javax.swing.JMenuItem Categoria;
    private javax.swing.JMenuItem MovimientoMensual;
    private javax.swing.JMenuItem MovimientoRapido;
    private javax.swing.JMenuItem MovimientosImpagos;
    private javax.swing.JMenuItem MovimientosPagos;
    private javax.swing.JMenuItem MovimientosPorCategorias;
    private javax.swing.JMenuItem Resumen;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JDesktopPane fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
